### ISSUE TITLE
Microsoft.Cci.Pdb.PdbDebugException: Unknown custom metadata item kind: 6 - Raspbian

### ISSUE THREAD

**Issue by mikolus** [techl/MonoRemoteDebugger#13]
Hi,
I'm trying to debug one of my projects on Raspberry PI (Raspbian).
When I start debugging, I'm getting this:

> Fatal error:
> Microsoft.Cci.Pdb.PdbDebugException: Unknown custom metadata item kind: 6
>   at Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata (Microsoft.Cci.Pdb.BitAccess bits) [0x00000] in <filename unknown>:0
>   at Microsoft.Cci.Pdb.PdbFunction..ctor (System.String module, ManProcSym proc, Microsoft.Cci.Pdb.BitAccess bits) [0x00000] in <filename unknown>:0
>   at Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions (System.String module, Microsoft.Cci.Pdb.BitAccess bits, UInt32 limit, Boolean readStrings) [0x00000] in <filename unknown>:0
>   at Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule (Microsoft.Cci.Pdb.BitAccess bits, Microsoft.Cci.Pdb.DbiModuleInfo info, Microsoft.Cci.Pdb.IntHashTable names, System.Collections.ArrayList funcList, Boolean readStrings, Microsoft.Cci.Pdb.MsfDirectory dir, System.Collections.Generic.Dictionary`2 nameIndex, Microsoft.Cci.Pdb.PdbReader reader) [0x00000] in <filename unknown>:0
>   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions (System.IO.Stream read, Microsoft.Cci.Pdb.BitAccess bits, Boolean readAllStrings) [0x00000] in <filename unknown>:0
>   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions (System.IO.Stream read, Boolean readAllStrings) [0x00000] in <filename unknown>:0
>   at Pdb2Mdb.Driver.Convert (Mono.Cecil.AssemblyDefinition assembly, System.IO.Stream pdb, Mono.CompilerServices.SymbolWriter.MonoSymbolWriter mdb) [0x00000] in <filename unknown>:0

Then the application runs, but without Visual Studio catching exceptions or breakpoints.
I was able to debug almost almost empty console app with just Console.ReadLine(); in it.

**Comment by makuhlmann** [comment]
Same issue for me, except that the application won't even run.

**Comment by techcap** [comment]
I think there may be some conflict with other visual studio extensions. Could you check it?

**Comment by gerardwknight** [comment]
I get the same error  Visual Studio 2015 Community Edition connecting to the remote debug server running on a Beagle Bone Black C with Debian. How do I check for a conflict with other extensions?

**Comment by gerardwknight** [comment]
The pdb error is resolved by using an updated version of  pdb2mdb, see 
http://stackoverflow.com/questions/36900315/how-can-i-remotely-debug-a-c-sharp-net-4-5-winforms-application-on-a-raspberry

but then breakpoints don't work at all, with anything more complicated than a hello world app with a console.WriteLine breakpoint.

**Comment by techcap** [comment]
Did you use the latest version, v1.0.7?

**Comment by gerardwknight** [comment]
Yes I used v1.0.7, I'm going to try and use MonoDevelop softdebugging on the same system, and see if that works. I will let you know how it goes. Is there anything else I can do to help diagnose the problem?

**Comment by techcap** [comment]
@mikolus @etlam5123 Could you check the mono version? When I used mono v3.x, I get same errors.
After updating to v4.2.3.4, the problem was solved.

**Comment by techcap** [comment]
@gerardwknight Could you explain more detail about "with anything more complicated than a hello world app"? Now it doesn't support the breakpoint on user threads.
