### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by rocuh** [techl/MonoRemoteDebugger#14]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.0.6
### Description

Method not found on client, it is conflicting with the latest xamarin debugger (i'm using 4.1.0.462) they've added optional parameters to Connect it looks like:

`VirtualMachine Mono.Debugger.Soft.VirtualMachineManager.Connect(IPEndPoint endpoint, TextWriter logWriter = null)`

 Copying the latest Mono.Debugger.Soft.dll and rebuilding fixes it, no other changes.
### Steps to recreate

Install xamarin 4.1.0.462 you will get this error

**Comment by techcap** [comment]
Please check again using v1.0.7.
I used Mono.Debugger.Soft.dll from Xamarin Studion 5.10.3 build 51.
There is no version information in Mono.Debugger.Soft.dll. So I cannot sure which one is the latest version.

**Comment by rocuh** [comment]
No thats diferent than the one that gets installed with vs, i used the one from here:

C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Xamarin\Xamarin\4.1.0.462

If you go your StartDebugging method where you do the following:

`
_vm = VirtualMachineManager.Connect(new IPEndPoint(_ipAddress, 11000));`

On intellisense you will see the Connect now has two parameters with the one with visual studio (the second parameter defaulting to null).

**Comment by techcap** [comment]
Where did you get the version 4.1.0.462? When I installed through xamarin.com, the version v4.0.4.4 is installed now.
I changed dll name for avoiding conflict. Could you check v1.0.8?

**Comment by techcap** [comment]
I changed mono related reference dlls to custom build dlls because of dll conflicts.
Please use the version v1.0.10.
