### ISSUE TITLE
Error:  Unable to start program 

### ISSUE THREAD

**Issue by maddig** [techl/MonoRemoteDebugger#2]
Hi. I have error when press "connect" like "Unable to start program" ... method is not exist 

Windows Firewall is off, VS 2015 run as administrator

LogFile:

2016-01-20 22:29:22.7067|TRACE|MonoRemoteDebugger.Debugger.DebugHelper|AD7Engine (entering) :  SetRegistryRoot
2016-01-20 22:29:22.7067|TRACE|MonoRemoteDebugger.Debugger.DebugHelper|AD7Engine (entering) :  SetLocale
2016-01-20 22:29:22.7067|TRACE|MonoRemoteDebugger.Debugger.DebugHelper|AD7Engine (entering) :  LaunchSuspended
2016-01-20 22:29:22.7067|ERROR|MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension|System.Runtime.InteropServices.COMException (0x89710016): Unable to start program 'D:\Work\VS\temp\ConsoleApplication4\ConsoleApplication4\bin\Debug\ConsoleApplication4.exe'.

Метод не существует.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.<AttachDebugger>d__7.MoveNext()
2016-01-20 22:29:22.7067|ERROR|MonoRemoteDebugger.VSExtension.MonoDebuggerPackage|System.Runtime.InteropServices.COMException (0x89710016): Unable to start program 'D:\Work\VS\temp\ConsoleApplication4\ConsoleApplication4\bin\Debug\ConsoleApplication4.exe'.

Метод не существует.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.<AttachDebugger>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoRemoteDebugger.VSExtension.MonoDebuggerPackage.<StartSearching>d__11.MoveNext()

**Comment by techcap** [comment]
Did you launch MonoRemoteDebugger.Server and have proper permission on target device?

**Comment by maddig** [comment]
Yes of course, i launch MonoRemoteDebugger.Server under root user but i didn't set any permission yet. I see console message that my client is connected, but when i connect in VS2015 i have error message. Maybe should i give permission in Win 10? One thing is interesting. I have english VS2015 but error message contains local for my win10 words like "Метод не существует" (method is not exists). For target device i use Raspberry PI with raspbian.

**Comment by AndrosovIgor** [comment]
Hi, I have the same issue (VS 2015 + Mono running on Raspbian)

I attach log of server
![log](https://cloud.githubusercontent.com/assets/8581621/12478688/eac760c0-c03e-11e5-856f-c6f755437ab1.PNG)

**Comment by techcap** [comment]
Please use the server ver1.0.2. Refer to the description. https://github.com/techl/MonoRemoteDebugger/blob/master/README.md

**Comment by ghost** [comment]
Hello, got the same problem here. Getting a message saying that the method does not exist.

La méthode n'existe pas.
   à System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   à System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   à MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.<AttachDebugger>d__7.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à MonoRemoteDebugger.VSExtension.MonoDebuggerPackage.<StartSearching>d__11.MoveNext()
2016-02-04 04:31:42.1985|TRACE|MonoRemoteDebugger.Debugger.DebugHelper|AD7Engine (entering) :  SetRegistryRoot
2016-02-04 04:31:42.1985|TRACE|MonoRemoteDebugger.Debugger.DebugHelper|AD7Engine (entering) :  SetLocale
2016-02-04 04:31:42.1985|TRACE|MonoRemoteDebugger.Debugger.DebugHelper|AD7Engine (entering) :  LaunchSuspended
2016-02-04 04:31:42.1985|ERROR|MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension|System.Runtime.InteropServices.COMException (0x89710016): Impossible de démarrer le programme 'D:\Documents\RaspPI\TestRaspMono1\TestRaspMono1\bin\Debug\TestRaspMono1.exe'. 

La méthode n'existe pas.
   à System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   à System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   à MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.<AttachDebugger>d__7.MoveNext()
2016-02-04 04:31:42.1985|ERROR|MonoRemoteDebugger.VSExtension.MonoDebuggerPackage|System.Runtime.InteropServices.COMException (0x89710016): Impossible de démarrer le programme 'D:\Documents\RaspPI\TestRaspMono1\TestRaspMono1\bin\Debug\TestRaspMono1.exe'. 

La méthode n'existe pas.
   à System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   à System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   à MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.<AttachDebugger>d__7.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à MonoRemoteDebugger.VSExtension.MonoDebuggerPackage.<StartSearching>d__11.MoveNext()

**Comment by maddig** [comment]
Hi. I think it problem related with Windows 10. I don't have problem with remote debugger in Windows 8.1 but under Win10 i had the same error.

To **gabrielsoze** which OS do you use?

**Comment by ghost** [comment]
Hello,

Thanks for the feedback, I will check with my other dev machine and see if it Works under win 7

Regards 

JF Hautenauven

Envoyé de mon iPhone

**Comment by ghost** [comment]
Hello,

Tested here with Windows 7 and Windows 8.1, same error

Best regards,

De : maddig [mailto:notifications@github.com] 
Envoyé : jeudi 4 février 2016 07:43
À : techl/MonoRemoteDebugger MonoRemoteDebugger@noreply.github.com
Cc : gabrielsoze jf.hautenauven@gmail.com
Objet : Re: [MonoRemoteDebugger] Error: Unable to start program (#2)

Hi. I think it problem related with Windows 10. I don't have problem with remote debugger in Windows 8.1 but under Win10 i had the same error.

**Comment by techcap** [comment]
I tested on the machine, win10 x64 Visual Studio 2015 Enterprise Update 1 to raspberry pi 2 rasbian kernel 4.1.11-v7+ and mono 4.0.4.1. It works properly.

**Comment by techcap** [comment]
Can you upload the log file in MonoRemoteDebugger/Log/MonoRemoteDebugger.log

**Comment by ghost** [comment]
Please find attached the log file requested.

Best regards,

JF Hautenauven

De : techcap [mailto:notifications@github.com] 
Envoyé : mercredi 17 février 2016 10:02
À : techl/MonoRemoteDebugger MonoRemoteDebugger@noreply.github.com
Cc : gabrielsoze jf.hautenauven@gmail.com
Objet : Re: [MonoRemoteDebugger] Error: Unable to start program (#2)

Can you upload the log file in MonoRemoteDebugger/Log/MonoRemoteDebugger.log


Reply to this email directly or view it on GitHub
<http://s.bl-1.com/h/wSjKwWB?url=https://github.com/techl/MonoRemoteDebugger
/issues/2#issuecomment-185104436> .
<https://github.com/notifications/beacon/AQRKLlHNW8-aJrRdrizWHwojtRIuIhRnks5
plC6igaJpZM4HI8_k.gif> 

  http://s.bl-1.com/ny98m6S.gif

**Comment by maddig** [comment]
Hi, guys. I think I have found problem. The problem was related with Xamarin components, that I installed with VS2015. After uninstall Xamarin components, debugger works well.

**Comment by ghost** [comment]
Hello, Thanks for the feedback, I will try

Best regards,

De : maddig [mailto:notifications@github.com] 
Envoyé : lundi 29 février 2016 22:21
À : techl/MonoRemoteDebugger MonoRemoteDebugger@noreply.github.com
Cc : gabrielsoze jf.hautenauven@gmail.com
Objet : Re: [MonoRemoteDebugger] Error: Unable to start program (#2)

Hi, guys. I think I have found problem. The problem was related with Xamarin components, that I installed with VS2015. After uninstall Xamarin components, debugger works well.

**Comment by cooldude85** [comment]
After uninstalling Xamarin components the debugging started to work for me but for only one line of program. As soon as I write few more lines of code the beakpoint do not hit at all and I do get the exception on linux:
![image](https://cloud.githubusercontent.com/assets/12986170/13624294/c0dc5554-e5d2-11e5-9de4-aa62f7e80bfc.png)

FYI: I am using the latest version of mono-complete of linux.

Please help me out with this error.
Thanks

**Comment by techcap** [comment]
@pankajsachdeva85 Why don't you remove mono and install again?

**Comment by cooldude85** [comment]
Thanks @techcap reinstalling mono did work. Issue resolved.

**Comment by michidk** [comment]
Well, i have exactly the same problem as @maddig. Using 1.0.3
![error](https://cloud.githubusercontent.com/assets/3979930/14018000/80300d16-f1cb-11e5-8f30-96cd9e245007.png) 
The error says "The method don't exists."
I uninstalled all xamarin releated vs addons, i run vs as administrator, the mono process runs on the root account. 
This is the server log: http://pastebin.com/KDxrxnVN 
The client log: http://pastebin.com/L7f08VTf

**Comment by ghost** [comment]
For the update on my side, tried all the previously talked solutions and so far , no progress on the issue...

I have abandoned the idea for the moment, busy on other stuff .

But I m still interested if a real solution was to show up

Best regards and keep the good work going,

JF Hautenauven

Envoyé de mon iPhone

**Comment by techcap** [comment]
Please use v1.0.4. "Method does not exist" problem is fixed. It is related to the Xamarin VS extension.
