### ISSUE TITLE
Port 15000 is in use

### ISSUE THREAD

**Issue by dhearn** [techl/MonoRemoteDebugger#20]
### Installed product versions
- Visual Studio: Visual Studio 2015 Professional
- This extension: 1.0.8 (I think, latest from Visual Studio gallery website which reports it as 1.0.8 but Visual Studio reports it as 1.0.5)
- Server: 1.0.7 (later versions failed to work due to issue https://github.com/techl/MonoRemoteDebugger/issues/18)
### Description

Starting MonoRemoteDebugger from Visual Studio displays a "Port 15000 is in use" message box.  This appears to be because Kaspersky Endpoint Security 10 is installed (klnagent.exe) which already listens on port 15000 (see https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers).
### Steps to recreate
1. Have some software installed which listens on port 15000 (e.g. klnagent.exe)
2. Launch MonoRemoteDebugger in VS
3. See "Port 15000 is in use" popup
4. Popup can be cleared and then proceed to server selection, but no auto-discovery possible, requiring manual IP entry only.
### Possible solutions
1. Use another port number which was not already used by software which may be mandated by organisation's network admins and cannot be disabled.
2. Alternatively, provide a facility for users to specify their own port numbers in both VS extension and server components.

**Comment by techcap** [comment]
I'll change the port in the next version. Thanks^^
