### ISSUE TITLE
Fatal Error when remote debugging on Raspberry Pi

### ISSUE THREAD

**Issue by davidsk** [techl/MonoRemoteDebugger#23]
I'm running Visual Studio 2015 Update 3 (14.0.25425.01) on Win10 (10586.545) and attempting to remote debug on a Raspberry Pi Model B Rev1 on Raspbian Jessie.

I have installed the Visual Studio extension (1.0.11) and MonoRemoteDebugger on the pi.  After I have selected remote debugging in Visual Studio and have provided the IP of the pi, there's a couple of seconds delay and then Visual Studio displays the "Did not receive an answer in time" message.  The debug server continues to run on the pi but reports "Fatal error: Microsoft.Cci.Pdb.PdbDebugException: Unknown custom metadata item kind : _x_" once for each project

Any help would be appreciated.

**Comment by techcap** [comment]
What mono version did you use in raspbian? I tested with v4.4.0.

**Comment by davidsk** [comment]
I'm running mono 3.2.8?
`mono --version`
`Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-10)`

I installed using apt-get just a couple of days ago so I'm surprised that the versions are so different.

**Comment by techcap** [comment]
Please refer to this site.
http://www.mono-project.com/docs/getting-started/install/linux/

**Comment by davidsk** [comment]
Just followed those instructions and got a bunch of Illegal instruction messages, which I also get when I run mono --version.

**Comment by techcap** [comment]
This is what I used.

```
#Adding source
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list

#For mod_mono, libgdiplus
echo "deb http://download.mono-project.com/repo/debian wheezy-apache24-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list
echo "deb http://download.mono-project.com/repo/debian wheezy-libjpeg62-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list

#Update & Upgrade
apt-get update -y
apt-get install mono-devel mono-complete referenceassemblies-pcl ca-certificates-mono mono-xsp4 -y

#Install libuv
sudo apt-get install make automake libtool curl -y
curl -sSL https://github.com/libuv/libuv/archive/v1.9.1.tar.gz | sudo tar zxfv - -C /usr/local/src
cd /usr/local/src/libuv-1.9.1
sudo sh autogen.sh
sudo ./configure
sudo make
sudo make install
sudo rm -rf /usr/local/src/libuv-1.9.1 && cd ~/
sudo ldconfig
```
