### ISSUE TITLE
What does "Not supported breakpoint on user thread" mean?

### ISSUE THREAD

**Issue by dlahmad** [techl/MonoRemoteDebugger#33]
Dear Developer,

as far as i understand it you can set breakpoints. In which cases one cannot set them? 
What exactly does user thread mean in this context?

Thanks in advance and best regards

**Comment by techcap** [comment]
Currently, setting breakpoints works only in main thread.

**Comment by dlahmad** [comment]
@techcap Thank you very much for the information.
