### ISSUE TITLE
Ability to designate a port with remote IP

### ISSUE THREAD

**Issue by ghost** [techl/MonoRemoteDebugger#34]
### Installed product versions
- Visual Studio: [2015 Professional/Community]
- This extension: [1.0.12]

### Description
The ability to designate which port to connect to when attempting to target a remote IP would be awesome if possible.  We run local development machines using Docker and about 30 services all running on mono, I can tell Docker to expose 13001 for all the containers, but each of the containers will have a random port like 32878 or something similar.  Currently if you attempt to pass a port in when putting in a remote IP such as "10.240.3.20:32787" you get an error "An invalid IP address was specified".

### Steps to recreate
1. Start container with mono debugging enabled and expose port 13001
2. Docker then gives 13001 a new random port
3. Attempt to connect to machine through VS using IP and port number in "IP:PORT" format
4. Error popup "An invalid IP address was specified"

### Current behavior
Remote IP field does not accept a port with the IP.

### Expected behavior
Remote IP field or a new field accepts a port number giving the ability to target any IP and port.

**Comment by techcap** [comment]
Can you try this?

https://github.com/techl/MonoRemoteDebugger/releases/tag/v1.2.0

Before using this, please adjust parameters ServerPort or DebuggerAgentPort on MonoRemoteDebugger.Server.exe.config.
