### ISSUE TITLE
The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG)) on BBB

### ISSUE THREAD

**Issue by PhyscoSmurf** [techl/MonoRemoteDebugger#36]
### Installed product versions
- Visual Studio: 2017 Community
- This extension: 1.1.0

### Description
Trying to use this on a BeagleBone Black, it would be very nice to be able to run C# and Debug. Any help would be greatly appreciated as I have a project that I was thinking of using C# on but if I can't debug then whats the point right? 

My BeagleBone Black is running Debian 8 if that helps.

### Steps to recreate
Click on MonoRemoteDebugger

### Current behavior
Exception

### Expected behavior
Work

**Comment by techcap** [comment]
What was your mono version? Was it latest?

**Comment by PhyscoSmurf** [comment]
@techcap I am so sorry, I could of sworn I added that, I am running: Mono JIT compiler version 4.8.1 (Stable 4.8.1.0/22a39d7). Also I have the BeagleBone Black hooked up to a network via wired Ethernet. I can confirm that it is visible and able to accept a connection because I can browse directly to its Apache Web Server @ 192.168.7.2. I am wondering if I need to specify a port in the configuration somewhere?

**Comment by techcap** [comment]
I didn't test on BBB. You may check the port conflict. New version support changing port.
