### ISSUE TITLE
Problem VS 2013 instalation

### ISSUE THREAD

**Issue by nikko24** [techl/MonoRemoteDebugger#38]
### Installed product versions
- Visual Studio 2013 Ultima
- This extension: 1.1.21

### Description
Problem with instalation

### Steps to recreate
1. I download it
2. Run the instaler
3. Fail 
![image](https://cloud.githubusercontent.com/assets/15264150/26405425/8d2778d2-4095-11e7-8746-d940153d88a2.png)

This is from install log:

24. 5. 2017 15:23:31 - Microsoft VSIX Installer
24. 5. 2017 15:23:31 - -------------------------------------------
24. 5. 2017 15:23:31 - Initializing Install...
24. 5. 2017 15:23:31 - Extension Details...
24. 5. 2017 15:23:31 - 	Identifier      : 27D183E9-5D2B-44D6-9EC8-2DB329096DF7
24. 5. 2017 15:23:31 - 	Name            : MonoRemoteDebugger
24. 5. 2017 15:23:31 - 	Author          : Techl.com
24. 5. 2017 15:23:31 - 	Version         : 1.2.0
24. 5. 2017 15:23:31 - 	Description     : MonoRemoteDebugger
24. 5. 2017 15:23:31 - 	Locale          : en-US
24. 5. 2017 15:23:31 - 	MoreInfoURL     : https://github.com/techl/MonoRemoteDebugger
24. 5. 2017 15:23:31 - 	InstalledByMSI  : False
24. 5. 2017 15:23:31 - 	SupportedFrameworkVersionRange : [4.5,)
24. 5. 2017 15:23:31 - 
24. 5. 2017 15:23:31 - 	Supported Products : 
24. 5. 2017 15:23:31 - 		Microsoft.VisualStudio.Pro
24. 5. 2017 15:23:31 - 			Version : [13.0,15.0]
24. 5. 2017 15:23:31 - 		Microsoft.VisualStudio.Ultimate
24. 5. 2017 15:23:31 - 			Version : [13.0,15.0]
24. 5. 2017 15:23:31 - 		Microsoft.VisualStudio.Premium
24. 5. 2017 15:23:31 - 			Version : [13.0,15.0]
24. 5. 2017 15:23:31 - 		Microsoft.VisualStudio.VSWinDesktopExpress
24. 5. 2017 15:23:31 - 			Version : [13.0,15.0]
24. 5. 2017 15:23:31 - 		Microsoft.VisualStudio.VWDExpress
24. 5. 2017 15:23:31 - 			Version : [13.0,15.0]
24. 5. 2017 15:23:31 - 		Microsoft.VisualStudio.Community
24. 5. 2017 15:23:31 - 			Version : [14.0,15.0]
24. 5. 2017 15:23:31 - 
24. 5. 2017 15:23:31 - 	References      : 
24. 5. 2017 15:23:31 - 		-------------------------------------------------------
24. 5. 2017 15:23:31 - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
24. 5. 2017 15:23:31 - 		Name         : Visual Studio MPF 14.0
24. 5. 2017 15:23:31 - 		Version      : [14.0]
24. 5. 2017 15:23:31 - 		MoreInfoURL  : 
24. 5. 2017 15:23:31 - 		Nested       : No
24. 5. 2017 15:23:31 - 
24. 5. 2017 15:23:31 - 
24. 5. 2017 15:23:31 - Searching for applicable products...
24. 5. 2017 15:23:31 - Found installed product - Microsoft Visual Studio Ultimate 2013
24. 5. 2017 15:23:31 - Found installed product - Microsoft Visual Studio Premium 2013
24. 5. 2017 15:23:31 - Found installed product - Microsoft Visual Studio Professional 2013
24. 5. 2017 15:23:31 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
24. 5. 2017 15:23:31 - Found installed product - Global Location
24. 5. 2017 15:23:31 - Found installed product - ssms
24. 5. 2017 15:23:31 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   v VSIXInstaller.App.InitializeInstall()
   v System.Threading.Tasks.Task.InnerInvoke()
   v System.Threading.Tasks.Task.Execute()

**Comment by techcap** [comment]
Current version doesn't support VS2013. Please use VS2017 community edition.

**Comment by nikko24** [comment]
I have only VS 2013, please do you have old version for VS 2013?

**Comment by techcap** [comment]
Can you try this one? I just removed the requirement of VS2015 or above. I didn't test it in VS2013.

[MonoRemoteDebugger.VSExtension.zip](https://github.com/techl/MonoRemoteDebugger/files/1030928/MonoRemoteDebugger.VSExtension.zip)

**Comment by techcap** [comment]
@nikko24 Did you check?

**Comment by nikko24** [comment]
@techcap Yes, but on VS 2013 didnt work, i installed VS 2017.

**Comment by techcap** [comment]
I see.
