### ISSUE TITLE
C# Remote Debugging fails

### ISSUE THREAD

**Issue by pmeloy** [techl/MonoRemoteDebugger#45]
Just a note, instructions for use could be a little more verbose. 

### Installed product versions
VS2015 Community
14.0.25431.01 update 3

### Description
Won't actually debug program
Was giving unable to find pdb error then I enabled microsoft symbol server and that message went away. It also gave
Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.VisualStudio.HostingProcess.Utilities.dll
which has not gone away.

### Steps to recreate
Open C# solution on Raspberry from Win10 VS2015
Select MonoRemoteDebugger->Debug with Mono(remote)
### Current behavior
Local show program but doesn't debug .Doesn't even run program remotely

### Expected behavior
Debug programs

**Comment by pmeloy** [comment]
Rewrote my Raspbian SD card and in the new install the remote debugging works fine. Must have been something broken in the old installation.

**Comment by techcap** [comment]
👍
