### ISSUE TITLE
Passing parameters to main

### ISSUE THREAD

**Issue by gnac** [techl/MonoRemoteDebugger#46]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.3.0

### Description
Is it possible to pass parameters to main? When a remote debug session is started, I only see the server parameters, but no way to pass parameters to the program under development. Is there a way to do this?

### Steps to recreate
1. Create an application that expects at least one parameter
2. Start a remote debugger session. 

### Current behavior
There does not appear to be a way to pass parameters to the main application.

### Expected behavior
There should be a way to pass parameters to main so that the program under development will execute as close to the deployed environment as possible.

**Comment by techcap** [comment]
Supported on v1.5.0
