### ISSUE TITLE
[QUESTION] Why MonoRemoteDebugger depends on MIEngine?

### ISSUE THREAD

**Issue by tibel** [techl/MonoRemoteDebugger#5]
May you explain why MonoRemoteDebugger depends on MIEngine (https://github.com/Microsoft/MIEngine)?
- Microsoft.DebugEngineHost.dll
- Microsoft.MICore.dll

I'm trying to understand the code and I couldn't figure out the reason for this.
Also the original project did not https://github.com/giessweinapps/MonoDebugger depend on it.

**Comment by techcap** [comment]
I tried not to copy the code from MIEngine but to refer it. MIEngine is opensourced and on going project, so I think using MIEngine as intact as possible will be better for the future.

**Comment by tibel** [comment]
So the old MonoDebugger copied/duplicated code?

**Comment by techcap** [comment]
I don't know. But when I checked MonoDebugger, there were some duplicated codes.

**Comment by tibel** [comment]
Thanks

**Comment by techcap** [comment]
:+1:
