### ISSUE TITLE
Can't run MonoRemoteDebugger.Server

### ISSUE THREAD

**Issue by monoluser** [techl/MonoRemoteDebugger#50]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 1.3.0

### Description
Replace this text with a short description

### Steps to recreate
1. Install on Ubuntu 18.04.2 LTS:
mono-runtime
mono-reference-assemblies-2.0
mono-reference-assemblies-4.0
libmono-posix4.0-cil
libmono-system-core4.0-cil

2. Run:
mono MonoRemoteDebugger.Server.exe

### Current behavior
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a00039a due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a00039a due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a0003aa due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a00039a due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a00039a due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a0003aa due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a00039a due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a00039a due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a0003aa due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a00039a due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a00039a due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a0003aa due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a00039a due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a00039a due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a0003aa due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a00039a due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a00039a due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a0003aa due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a000398 due to Could not load file or assembly or one of its dependencies. assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a00039a due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a00039a due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
Can't find custom attr constructor image: /home/luser/tmp/NLog.dll mtoken: 0x0a0003aa due to Could not load file or assembly or one of its dependencies. assembly:System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>
2019-02-27 11:52:58.9460|TRACE|MonoRemoteDebugger.SharedLib.Server.MonoUtils|Platform=Unix, GetMonoPath=mono, GetMonoXsp4=xsp4, GetPdb2MdbPath=pdb2mdb
Cannot open assembly '/usr/lib/mono/4.5/pdb2mdb.exe': No such file or directory.
2019-02-27 11:52:59.0174|TRACE|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|Start announcing
2019-02-27 11:52:59.5095|INFO|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|Waiting for client
2019-02-27 11:53:14.4863|INFO|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|Accepted client: 192.168.42.42:53007

Unhandled Exception:
System.AggregateException: One or more errors occurred. ---> System.TypeLoadException: Could not load type 'MonoRemoteDebugger.SharedLib.TcpCommunication' from assembly 'MonoRemoteDebugger.SharedLib, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'.
  at MonoRemoteDebugger.SharedLib.Server.MonoDebugServer.StartListening (System.Threading.CancellationToken token) [0x00057] in <774b6a28ae47478e896b75e30caf594e>:0
  at MonoRemoteDebugger.SharedLib.Server.MonoDebugServer.<Start>b__5_0 () [0x0000c] in <774b6a28ae47478e896b75e30caf594e>:0
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in <8f2c484307284b51944a1a13a14c0266>:0
  at System.Threading.Tasks.Task.Execute () [0x00016] in <8f2c484307284b51944a1a13a14c0266>:0
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00014] in <8f2c484307284b51944a1a13a14c0266>:0
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00052] in <8f2c484307284b51944a1a13a14c0266>:0
  at System.Threading.Tasks.Task.Wait () [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0
  at MonoRemoteDebugger.SharedLib.Server.MonoDebugServer.WaitForExit () [0x00000] in <774b6a28ae47478e896b75e30caf594e>:0
  at MonoRemoteDebugger.Server.Program.Main (System.String[] args) [0x0001c] in <276b70c3092d4533aca9ed66e835f587>:0
---> (Inner Exception #0) System.TypeLoadException: Could not load type 'MonoRemoteDebugger.SharedLib.TcpCommunication' from assembly 'MonoRemoteDebugger.SharedLib, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'.
  at MonoRemoteDebugger.SharedLib.Server.MonoDebugServer.StartListening (System.Threading.CancellationToken token) [0x00057] in <774b6a28ae47478e896b75e30caf594e>:0
  at MonoRemoteDebugger.SharedLib.Server.MonoDebugServer.<Start>b__5_0 () [0x0000c] in <774b6a28ae47478e896b75e30caf594e>:0
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in <8f2c484307284b51944a1a13a14c0266>:0
  at System.Threading.Tasks.Task.Execute () [0x00016] in <8f2c484307284b51944a1a13a14c0266>:0 <---

2019-02-27 11:53:14.5010|ERROR|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|System.AggregateException: One or more errors occurred. ---> System.TypeLoadException: Could not load type 'MonoRemoteDebugger.SharedLib.TcpCommunication' from assembly 'MonoRemoteDebugger.SharedLib, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'.
  at MonoRemoteDebugger.SharedLib.Server.MonoDebugServer.StartListening (System.Threading.CancellationToken token) [0x00057] in <774b6a28ae47478e896b75e30caf594e>:0
  at MonoRemoteDebugger.SharedLib.Server.MonoDebugServer.<Start>b__5_0 () [0x0000c] in <774b6a28ae47478e896b75e30caf594e>:0
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in <8f2c484307284b51944a1a13a14c0266>:0
  at System.Threading.Tasks.Task.Execute () [0x00016] in <8f2c484307284b51944a1a13a14c0266>:0
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.WaitAll (System.Threading.Tasks.Task[] tasks, System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00242] in <8f2c484307284b51944a1a13a14c0266>:0
  at System.Threading.Tasks.Task.WaitAll (System.Threading.Tasks.Task[] tasks, System.Int32 millisecondsTimeout) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0
  at MonoRemoteDebugger.SharedLib.Server.MonoDebugServer.Stop () [0x00040] in <774b6a28ae47478e896b75e30caf594e>:0
---> (Inner Exception #0) System.TypeLoadException: Could not load type 'MonoRemoteDebugger.SharedLib.TcpCommunication' from assembly 'MonoRemoteDebugger.SharedLib, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'.
  at MonoRemoteDebugger.SharedLib.Server.MonoDebugServer.StartListening (System.Threading.CancellationToken token) [0x00057] in <774b6a28ae47478e896b75e30caf594e>:0
  at MonoRemoteDebugger.SharedLib.Server.MonoDebugServer.<Start>b__5_0 () [0x0000c] in <774b6a28ae47478e896b75e30caf594e>:0
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in <8f2c484307284b51944a1a13a14c0266>:0
  at System.Threading.Tasks.Task.Execute () [0x00016] in <8f2c484307284b51944a1a13a14c0266>:0 <---

2019-02-27 11:53:14.5096|INFO|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|Closed MonoDebugServer
[ERROR] FATAL UNHANDLED EXCEPTION: System.AggregateException: One or more errors occurred. ---> System.TypeLoadException: Could not load type 'MonoRemoteDebugger.SharedLib.TcpCommunication' from assembly 'MonoRemoteDebugger.SharedLib, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'.
  at MonoRemoteDebugger.SharedLib.Server.MonoDebugServer.StartListening (System.Threading.CancellationToken token) [0x00057] in <774b6a28ae47478e896b75e30caf594e>:0
  at MonoRemoteDebugger.SharedLib.Server.MonoDebugServer.<Start>b__5_0 () [0x0000c] in <774b6a28ae47478e896b75e30caf594e>:0
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in <8f2c484307284b51944a1a13a14c0266>:0
  at System.Threading.Tasks.Task.Execute () [0x00016] in <8f2c484307284b51944a1a13a14c0266>:0
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00014] in <8f2c484307284b51944a1a13a14c0266>:0
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00052] in <8f2c484307284b51944a1a13a14c0266>:0
  at System.Threading.Tasks.Task.Wait () [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0
  at MonoRemoteDebugger.SharedLib.Server.MonoDebugServer.WaitForExit () [0x00000] in <774b6a28ae47478e896b75e30caf594e>:0
  at MonoRemoteDebugger.Server.Program.Main (System.String[] args) [0x0001c] in <276b70c3092d4533aca9ed66e835f587>:0
---> (Inner Exception #0) System.TypeLoadException: Could not load type 'MonoRemoteDebugger.SharedLib.TcpCommunication' from assembly 'MonoRemoteDebugger.SharedLib, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'.
  at MonoRemoteDebugger.SharedLib.Server.MonoDebugServer.StartListening (System.Threading.CancellationToken token) [0x00057] in <774b6a28ae47478e896b75e30caf594e>:0
  at MonoRemoteDebugger.SharedLib.Server.MonoDebugServer.<Start>b__5_0 () [0x0000c] in <774b6a28ae47478e896b75e30caf594e>:0
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in <8f2c484307284b51944a1a13a14c0266>:0
  at System.Threading.Tasks.Task.Execute () [0x00016] in <8f2c484307284b51944a1a13a14c0266>:0 <---

### Expected behavior
Well, have it work! ;)

**Comment by techcap** [comment]
Could you check your mono installation?

https://www.mono-project.com/download/stable/#download-lin

**Comment by monoluser** [comment]
Oh, thank you so much for your fast answer!
Yes, I was using an outdated version, works now like a charm!

Thanks again for your fast help!

**Comment by monoluser** [comment]
Back again...
Apparently, I can't evaluate any expressions at breakpoints, I'm always getting one of these errors:
```
Unable to evaluate the expression. Not implemented
Unsupported Expression
The expression cannot be evaluated while in run mode.
```

I've tried with all the PDB formats:
```
Portable
Pdb-only
Full
```

Any hints?

**Comment by monoluser** [comment]
Any news yet? Maybe I can help out somehow?

**Comment by monoluser** [comment]
What's the status? Do you need more input or my example project?

**Comment by TheColonel2688** [comment]
have you tried https://github.com/GordianDotNet/VSMonoDebugger ?

**Comment by techcap** [comment]
@monoluser What's your environment? 

My test environment:
# Remote Device
Ubuntu 18.04.1 LTS 4.19.13
Mono v5.18.0.240

# Local
Visual Studio 2017 .Net 4.5.2

![Imgur](https://i.imgur.com/rMUfRYM.png)

**Comment by monoluser** [comment]
And can you evaluate expressions in the Intermediate Window?

**Comment by techcap** [comment]
Immediate window is not supported.

**Comment by monoluser** [comment]
Do you plan to support it? That would be the main feature for me because I need to evaluate LINQ at breakpoints.

**Comment by techcap** [comment]
@monoluser I don't use that function. so, there is no plan to support currently.
