### ISSUE TITLE
Console.Writeline causes the exception

### ISSUE THREAD

**Issue by BorisTakara** [techl/MonoRemoteDebugger#56]
### Installed product versions
- Visual Studio:  2019 Professional
- This extension: 1.5.2

### Description
Console.Writeline("Hello") causes the exception.

Just a simple Hello World does not work. I could be wrong, but I do believe it worked with 2017 Proffessional.

### Steps to recreate
Here is my program:

       static void Main(string[] args)
        {
            int x = 6;
            x = 2 * x;
            Thread.Sleep(2000);
            try
            {
                Console.WriteLine("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

- On Beaglebone start the server: mono MonoRemoteDebugger.Server.exe
- On VisualStudio2019 Using Extensions/DebugWithMonoRemote  set a breakpoint on the 1st line and start HelloWorld program
- The bp is hit. I can single-step to Console.WriteLine
- Then the exception occurs: System.TypeInitializationException

The same program works fine without the debugger

**Comment by techcap** [comment]
What is your mono and VS version?

**Comment by BorisTakara** [comment]
VS-2019 Professional

mono -V ===> Mono JIT compiler version 6.6.0.160 (tarball Tue Dec  3 10:51:19 UTC 2019)

**Comment by laloutrejoyeuse** [comment]
Exactly the same problem for me, same mono JIT version (6.6.0.160). On a raspberry pi debian buster. Then the exception occurs (System.TypeInitializationException, System.ConsoleDriver --> dll not found) when the Console.WriteLine() instruction is executed.

**Comment by NateKomodo** [comment]
The same happens with DateTime, File, etc... completly unusable rn

**Comment by techcap** [comment]
Same problem #55
