### ISSUE TITLE
Did not receive an answer in time...

### ISSUE THREAD

**Issue by denis-ya** [techl/MonoRemoteDebugger#6]
Hi, do you have any idea why VS shows this error message when I start remote debug?
![error](http://s019.radikal.ru/i612/1602/6e/15994caf60f6.jpg)

**Comment by heartquake** [comment]
I have the same exact problem.

**Comment by benhysell** [comment]
I also just started seeing this issue...

**Comment by denis-ya** [comment]
I have two configurations (at home and at work)
1. Win10 x64 + Marvell mv5281/mono 3.10.0
2. Win 7 x64 +  i.MX6/mono 4.2.2.30
The first one works fine with VS2012/2015, but the second one reports this error. Which mono version do you use? Probably server part does not work with mono 4.2.

**Comment by benhysell** [comment]
I have two setups as well:
1. Win 10 x64 mono 4.2 to Ubuntu VM with mono 4.2 -- works fine
2. Win 10 x64 mono 4.2 to ARMv7 with mono 4.2 -- produces the error

I had Win 10 mono 4.2 going to the same ARMv7 with mono 3.2 and it did work ok...once I upgraded the ARMv7 to mono 4.2 I started seeing errors.

The logs do not say too much, from the server log:
2016-02-12 13:01:10.2108|INFO|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|Waiting for client
2016-02-12 13:01:10.1477|TRACE|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|Start announcing
2016-02-12 13:01:25.7054|INFO|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|Accepted client: 192.168.110.141:63919
2016-02-12 13:01:25.7628|INFO|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|Waiting for client

**Comment by denis-ya** [comment]
So, it works with 4.2, good.
As I understand, after that VS has to send files to server, but it does not do this.

**Comment by techcap** [comment]
I tested on the machine, win10 x64 Visual Studio 2015 Enterprise Update 1 to raspberry pi 2 rasbian kernel 4.1.11-v7+ and mono 4.0.4.1. It works properly.

**Comment by denis-ya** [comment]
Is it possible that mono has to be configured some specific way? I tried two mono devices with the same laptop, so Win10/VS15 + Marvell mv5281/mono 3.10.0 works fine, but Win10/VS15 +  i.MX6/mono 4.2.2.30 does not work. It has to be something wrong at my second mono device.

**Comment by techcap** [comment]
I tried also with mono v4.2.2.30. It works properly.
My test environment is Win10/VS15 + RaspberryPi2/mono 4.2.2.30.
So I think it is not related to mono version but linux environment.

**Comment by denis-ya** [comment]
Any ideas about linux environment? What could be wrong?

**Comment by techcap** [comment]
Can you upload the log file in MonoRemoteDebugger/Log/MonoRemoteDebugger.log

**Comment by denis-ya** [comment]
sure, please see the attached
[MonoRemoteDebugger.log.txt](https://github.com/techl/MonoRemoteDebugger/files/133953/MonoRemoteDebugger.log.txt)

**Comment by benhysell** [comment]
I have the same exact log.

I've dug a bit deeper, it seems to be crashing at:

[https://github.com/techl/MonoRemoteDebugger/blob/master/MonoRemoteDebugger.SharedLib/Server/ClientSession.cs#L47](https://github.com/techl/MonoRemoteDebugger/blob/master/MonoRemoteDebugger.SharedLib/Server/ClientSession.cs#L47)

Where it attempts to read the message sent from the client.

**Comment by techcap** [comment]
Can you give me also the log in the VS side?
Path : C:\Users{user id}\AppData\Local\Microsoft\VisualStudio\14.0\Extensions{random characters}\Log\MonoRemoteDebugger.log

**Comment by denis-ya** [comment]
Please see the attached VS log
[MonoRemoteDebugger.vs2015.log.txt](https://github.com/techl/MonoRemoteDebugger/files/135762/MonoRemoteDebugger.vs2015.log.txt)

**Comment by ManoloAlvarezForo** [comment]
I have the same error "Did not receive an answer in time... " in the log file this the message

2016-02-19 16:18:21.9500|ERROR|MonoRemoteDebugger.VSExtension.MonoDebuggerPackage|System.Exception: Did not receive an answer in time...
   at MonoRemoteDebugger.VSExtension.MonoClient.DebugSession.<WaitForAnswerAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MonoRemoteDebugger.VSExtension.MonoVisualStudioExtension.<AttachDebugger>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MonoRemoteDebugger.VSExtension.MonoDebuggerPackage.<StartSearching>d__11.MoveNext()
2016-02-19 16:28:30.3954|INFO|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|Closed MonoDebugServer
2016-02-19 16:28:33.5818|INFO|MonoRemoteDebugger.SharedLib.Server.MonoDebugServer|Closed MonoDebugServer

I have a virtual machine using linux and mono 4.2.2

**Comment by techcap** [comment]
@manoloalvaforo Could you send the vm image or can I access to the vm? If possible, please send to the email, techcap@live.com. I couldn't yet figure out it's related to server or client side.

**Comment by ManoloAlvarezForo** [comment]
Thanks for the help I'll try to send the vm image because I don't have the technical resources to send the vm image for the moment so can I send other information that you think help me to find the problem please

**Comment by techcap** [comment]
I found finally how to reproduce the problem. It's related to the linux side problem not VS side. Please give me a little time for figuring out.

**Comment by vincenttermaat** [comment]
is 12 days enough? :)

**Comment by techcap** [comment]
Please check the version v1.0.3.

**Comment by denis-ya** [comment]
Just compiled the extension from sources and tried it. Still have the same problem.
Please find the attached logs.
[MonoRemoteDebugger.log.txt](https://github.com/techl/MonoRemoteDebugger/files/167225/MonoRemoteDebugger.log.txt)
[MonoRemoteDebugger.vs2015.log.txt](https://github.com/techl/MonoRemoteDebugger/files/167224/MonoRemoteDebugger.vs2015.log.txt)

**Comment by techcap** [comment]
did you update the server also?

**Comment by denis-ya** [comment]
Yes, I used updated server as well

**Comment by techcap** [comment]
Can you check if pdb2mdb is installed properly?

**Comment by denis-ya** [comment]
How I can check this?

**Comment by techcap** [comment]
Just type pdb2mdb in the linux shell.
In my case , pdb2mdb is in /usr/bin/pdb2mdb.
pdb2mdb is included in the package 'mono-devel'.

**Comment by denis-ya** [comment]
do you mean i should run that at remote device? it says me
-sh: pdb2mdb: command not found

**Comment by techcap** [comment]
Yes. You have to install pdb2mdb on remote device.
Type

> sudo apt-get install mono-devel

**Comment by denis-ya** [comment]
Can I do it manually? I do not have app-get support at my target device.

**Comment by techcap** [comment]
I don't know about linux command well. 
But I think you have to build it from the source.
https://github.com/mono/mono/tree/master/mcs/tools/pdb2mdb

**Comment by denis-ya** [comment]
OK, thanks. I will try and report if it helps.

**Comment by denis-ya** [comment]
Do you mean I need to build pdb2mdb for target linux device or I can use pdb2mdb.exe?
I found pdb2mdb.exe on my target device 

```
root@ts-imx6-s:/usr/lib/mono/4.5# mono pdb2mdb.exe
Mono pdb to mdb debug symbol store converter
Usage: pdb2mdb assembly

```

**Comment by techcap** [comment]
Just put it in your path environment.

**Comment by denis-ya** [comment]
still have his problem

[MonoRemoteDebugger.log.txt](https://github.com/techl/MonoRemoteDebugger/files/168997/MonoRemoteDebugger.log.txt)
[MonoRemoteDebugger.vs2015.log.txt](https://github.com/techl/MonoRemoteDebugger/files/168998/MonoRemoteDebugger.vs2015.log.txt)

**Comment by techcap** [comment]
The log keeps saying 'cannot find the specified file', pdb2mdb.

**Comment by denis-ya** [comment]
I put pdb2mdb.exe this to /usr/bin and to folder with MonoRemoteDebugger.Server.exe

**Comment by denis-ya** [comment]
it also said about System.Net.Dns error. My target device does not have DNS support - do you think it can be a problem as well?

**Comment by denis-ya** [comment]
I resolved pdb2mdb issue, not it seems to be OK.

> root@ts-imx6-s:~# pdb2mdb
> Mono pdb to mdb debug symbol store converter
> Usage: pdb2mdb assembly
> root@ts-imx6-s:~# cd ~/Server/
> root@ts-imx6-s:~/Server# mono MonoRemoteDebugger.Server.exe

but I still cannot remote debug. For now it throws System.Net.Sockets.SocketException: Could not resolve host 'ts-imx6-s'
Please see the attached logs
[MonoRemoteDebugger.log.txt](https://github.com/techl/MonoRemoteDebugger/files/171876/MonoRemoteDebugger.log.txt)
[MonoRemoteDebugger.vs2015.log.txt](https://github.com/techl/MonoRemoteDebugger/files/171877/MonoRemoteDebugger.vs2015.log.txt)

**Comment by techcap** [comment]
I'll check it. Thanks for the report.

**Comment by denis-ya** [comment]
I have solved my problem by adding target device host name to hosts file. Now it works fine.
I also faced with error "Unable to start program - Method does not exist" and that was resolved by removing Xamarin. Am I right, that it is impossible to have both VS and Xamarin installed?

And just to summarize this - there were two issues causing the problem 
- pdb2mdb absence at target device
- target device could not resolve its ip by host name

Anyway thanks for your support.

**Comment by techcap** [comment]
After installing Xamain in VS, it says "Method does not exist". I'll figure out this problem.

**Comment by techcap** [comment]
Please check the version 1.0.4. I updated files related with Mono.

**Comment by hezhaowei** [comment]
fix this bug by change the server code MonoUtils.cs,  GetMonoRootPathWindows(), the registrykey of mono path is incorrect on Win10

**Comment by techcap** [comment]
@HarveyHe11 Thanks. I fixed it on v1.0.6.

**Comment by rocuh** [comment]
I also got this issue if you have a large DebugContent.zip that is deployed over a slow network, if it takes longer than 10s to download the zip it will show this. For some reason my raspberry pi network speed was not great. I increased the timeout and it was ok, maybe make this an option?

**Comment by Baks84** [comment]
Updated the code to enable providing the timeout when connecting.
Pull request was accepted by @techcap
