### ISSUE TITLE
Watch and stack

### ISSUE THREAD

**Issue by devcrafting** [techl/MonoRemoteDebugger#7]
Hello,

Is it normal to have only breakpoints, I cannot use watch (nor quick watch), nor navigate in call stack ? I got "Unsupported Expression" message

Regards
Clément

**Comment by techcap** [comment]
I think Watch works property. But Navigate in call stack does not.
![Image of working](http://i.imgur.com/GUvLY2i.png)

**Comment by devcrafting** [comment]
Thanks for you answer.
Yep, I though I had gave feedback on watch on this issue...sorry.
In fact, only local variable watch work, watching "this" does not (even if you put it in a local variable), nor parameters...but digging a little bit Soft-Mode Mono Debugger, I wonder if it would be possible in fact ?

**Comment by techcap** [comment]
Related to #11
